<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('products')->delete();
        
		\DB::table('products')->insert(array (
			0 => 
			array (
				'id' => 1,
				'user_id' => 1,
				'name' => 'Right Pack Expression',
				'code' => 'right-pack-expression',
				'description' => '<ol><li>Unique fabric application<br/></li><li>Suede leather bottom<br/></li><li>Internal sleeve fits 15&#34; laptop<br/></li><li>One large main compartment<br/></li><li>Straigh-cut,padded shoulder straps<br/></li><li>Front utility pocket with organizer<br/></li><li>Zippered front stash pocket<br/></li><li>Web haul handle<br/></li></ol>',
				'badge' => NULL,
				'price' => '4490.00',
				'sale_price' => NULL,
				'unit' => 5,
				'thumbnail_id' => 2,
				'created_at' => '2015-04-17 06:57:52',
				'updated_at' => '2015-04-17 07:00:59',
				'deleted_at' => NULL,
			),
			1 => 
			array (
				'id' => 2,
				'user_id' => 1,
				'name' => 'Superbreak - 1',
				'code' => 'superbreak-1',
				'description' => '<p>One large main compartment</p><p>Straight-cut, padded shoulder straps</p><p>Front utility pocket with organizer</p><p>2/3 padded back panel</p><p>Web haul handle<br/></p>',
				'badge' => NULL,
				'price' => '1990.00',
				'sale_price' => NULL,
				'unit' => 5,
				'thumbnail_id' => 6,
				'created_at' => '2015-04-17 07:01:43',
				'updated_at' => '2015-04-17 07:02:01',
				'deleted_at' => NULL,
			),
			2 => 
			array (
				'id' => 3,
				'user_id' => 1,
				'name' => 'Pilipinas',
				'code' => 'superbreak-pilipinas',
				'description' => '<p>Superbreak Pilippines design</p>',
				'badge' => NULL,
				'price' => '2000.00',
				'sale_price' => NULL,
				'unit' => 5,
				'thumbnail_id' => 0,
				'created_at' => '2015-04-17 07:15:52',
				'updated_at' => '2015-04-22 10:19:35',
				'deleted_at' => NULL,
			),
			3 => 
			array (
				'id' => 4,
				'user_id' => 1,
				'name' => 'Galaxy',
				'code' => 'superbreak-galaxy',
				'description' => '<p>Superbreak - Galaxy</p>',
				'badge' => NULL,
				'price' => '1500.00',
				'sale_price' => NULL,
				'unit' => 10,
				'thumbnail_id' => 0,
				'created_at' => '2015-04-17 07:18:31',
				'updated_at' => '2015-04-17 07:45:28',
				'deleted_at' => NULL,
			),
			4 => 
			array (
				'id' => 5,
				'user_id' => 1,
				'name' => 'Pink Mint Green',
				'code' => 'pink-mint-green',
				'description' => '<p>Overexposed - Pink Mint Green description</p>',
				'badge' => NULL,
				'price' => '1200.00',
				'sale_price' => NULL,
				'unit' => 5,
				'thumbnail_id' => 15,
				'created_at' => '2015-04-17 07:28:46',
				'updated_at' => '2015-04-21 08:48:28',
				'deleted_at' => NULL,
			),
			5 => 
			array (
				'id' => 6,
				'user_id' => 1,
				'name' => 'Big Student - Plain',
				'code' => 'big-student-plain',
				'description' => '<p>Big Student - Plain <br/></p>',
				'badge' => NULL,
				'price' => '1200.00',
				'sale_price' => NULL,
				'unit' => 8,
				'thumbnail_id' => 0,
				'created_at' => '2015-04-17 08:32:41',
				'updated_at' => '2015-04-17 08:32:53',
				'deleted_at' => NULL,
			),
			6 => 
			array (
				'id' => 7,
				'user_id' => 1,
				'name' => 'Benny Gold',
				'code' => 'benny-gold',
				'description' => '<p>Benny Gold description<br/></p>',
				'badge' => 'a:2:{s:5:"class";s:14:"ribbon-default";s:11:"class_array";a:1:{i:0;a:1:{s:4:"text";s:14:"ribbon-default";}}}',
				'price' => '2000.00',
				'sale_price' => NULL,
				'unit' => 1,
				'thumbnail_id' => 21,
				'created_at' => '2015-04-18 10:15:01',
				'updated_at' => '2015-04-21 08:37:41',
				'deleted_at' => NULL,
			),
			7 => 
			array (
				'id' => 8,
				'user_id' => 1,
				'name' => 'Dark Blue',
				'code' => 'right-pack-dark-blue',
				'description' => '<p>Right pack dark blue description<br/></p>',
				'badge' => NULL,
				'price' => '2000.00',
				'sale_price' => NULL,
				'unit' => 5,
				'thumbnail_id' => 22,
				'created_at' => '2015-04-21 08:38:20',
				'updated_at' => '2015-04-21 08:39:30',
				'deleted_at' => NULL,
			),
			8 => 
			array (
				'id' => 9,
				'user_id' => 1,
				'name' => 'Lacoste Polo',
				'code' => 'lacoste-polo',
				'description' => '<p>Lacoste Polo description<br/></p>',
				'badge' => NULL,
				'price' => '2000.00',
				'sale_price' => NULL,
				'unit' => 1,
				'thumbnail_id' => 0,
				'created_at' => '2015-04-21 08:43:30',
				'updated_at' => '2015-04-21 08:43:37',
				'deleted_at' => NULL,
			),
			9 => 
			array (
				'id' => 10,
				'user_id' => 1,
				'name' => 'Lacoste V-neck',
				'code' => 'lacoste-v-neck',
				'description' => '<p>Lacoste V-neck description<br/></p>',
				'badge' => NULL,
				'price' => '2000.00',
				'sale_price' => NULL,
				'unit' => 6,
				'thumbnail_id' => 0,
				'created_at' => '2015-04-21 08:44:02',
				'updated_at' => '2015-04-21 08:44:11',
				'deleted_at' => NULL,
			),
			10 => 
			array (
				'id' => 11,
				'user_id' => 1,
				'name' => 'Can Can Perfume',
				'code' => 'can-can-perfume',
				'description' => '<p>Famous beauty Paris Hilton launched her fourth fragrance for women, her 7th fragrance in general – Can Can. <br/></p><p>The fragrance is inspired by the film Moulin Rouge and the song Lady Marmalade.The fragrance is floral-fruity, oriental, and of course, very sensual. It opens with clementine blossom, black currant and nectarine. The heart unites wild orchid and orange blossom, while the base brings soft musk, amber and precious woods. The fragrance was designed by Jean-Claude Delville in 2007.<br/></p>',
				'badge' => NULL,
				'price' => '1500.00',
				'sale_price' => NULL,
				'unit' => 10,
				'thumbnail_id' => 0,
				'created_at' => '2015-04-21 08:44:41',
				'updated_at' => '2015-04-21 08:44:51',
				'deleted_at' => NULL,
			),
			11 => 
			array (
				'id' => 12,
				'user_id' => 1,
				'name' => 'Galaxy',
				'code' => 'overexposed-galaxy',
				'description' => '<p>Overexposed Galaxy Description<br/></p>',
				'badge' => NULL,
				'price' => '1500.00',
				'sale_price' => NULL,
				'unit' => 2,
				'thumbnail_id' => 0,
				'created_at' => '2015-04-21 08:45:30',
				'updated_at' => '2015-04-21 08:45:35',
				'deleted_at' => NULL,
			),
			12 => 
			array (
				'id' => 13,
				'user_id' => 1,
				'name' => 'Sling Bags Plain',
				'code' => 'sling-bags-plain',
				'description' => '<p>Sling Bags Plain description<br/></p>',
				'badge' => 'a:2:{s:5:"class";s:14:"ribbon-default";s:11:"class_array";a:1:{i:0;a:1:{s:4:"text";s:14:"ribbon-default";}}}',
				'price' => '800.00',
				'sale_price' => '500.00',
				'unit' => 20,
				'thumbnail_id' => 40,
				'created_at' => '2015-04-21 08:46:27',
				'updated_at' => '2015-04-22 04:20:19',
				'deleted_at' => NULL,
			),
			13 => 
			array (
				'id' => 14,
				'user_id' => 1,
				'name' => 'Neon',
				'code' => 'overexposed-neon',
				'description' => '<p>Overexposed Neon colors description<br/></p>',
				'badge' => NULL,
				'price' => '2000.00',
				'sale_price' => NULL,
				'unit' => 5,
				'thumbnail_id' => 0,
				'created_at' => '2015-04-21 08:48:02',
				'updated_at' => '2015-04-21 08:48:07',
				'deleted_at' => NULL,
			),
			14 => 
			array (
				'id' => 15,
				'user_id' => 1,
				'name' => 'Pinoy Ako T-shirt',
				'code' => 'pinoy-ako-t-shirt',
				'description' => '<p>Premium Designs</p><p>Ultra Cotton fabric</p><p>Premium Silk Screen</p><br/>',
				'badge' => 'a:2:{s:5:"class";s:14:"ribbon-default";s:11:"class_array";a:1:{i:0;a:1:{s:4:"text";s:14:"ribbon-default";}}}',
				'price' => '500.00',
				'sale_price' => '300.00',
				'unit' => 20,
				'thumbnail_id' => 0,
				'created_at' => '2015-04-22 10:22:19',
				'updated_at' => '2015-04-22 10:23:39',
				'deleted_at' => NULL,
			),
			15 => 
			array (
				'id' => 16,
				'user_id' => 1,
				'name' => 'Fashionice bags',
				'code' => 'fashionice-bags',
			'description' => '<p>Fashionice bags, BEA-BAGS  (ORIGINAL)</p><p><span>Colors: Red, Blue, Brown, Black, White, Copper</span><br/></p>',
				'badge' => 'a:2:{s:5:"class";s:14:"ribbon-default";s:11:"class_array";a:1:{i:0;a:1:{s:4:"text";s:14:"ribbon-default";}}}',
				'price' => '1200.00',
				'sale_price' => '800.00',
				'unit' => 10,
				'thumbnail_id' => 49,
				'created_at' => '2015-04-22 10:27:14',
				'updated_at' => '2015-04-22 10:46:08',
				'deleted_at' => NULL,
			),
			16 => 
			array (
				'id' => 17,
				'user_id' => 1,
				'name' => 'Dell XPS 12 Intel Haswell i7 8GB',
				'code' => 'dell-xps-12-intel-haswell-i7-8gb',
			'description' => '<h1>KWAN CORPORATION</h1><h4>Dell XPS 12 Intel Haswell i7 8GB 256SSD </h4><ul><li style="text-align: left;">Mall Price 90k, SALE PRICE: 50k</li><li style="text-align: left;">Bnew: Mall Display</li><li style="text-align: left;">Dell XPS12 9Q33</li><li style="text-align: left;"><span>Windows 8.1 Pro x64</span></li><li style="text-align: left;"><span>Intel Haswell Core i7-4510U Ultrabook Processor (2-3.1GHz)</span></li><li style="text-align: left;"><span>1.8GB Intel HD 4400</span></li><li style="text-align: left;"><span>8GB 1600MHz (8GB Max)</span></li><li style="text-align: left;"><span>256GB SSD</span></li><li style="text-align: left;"><span>12.5 FullHD (1920×1080)</span></li><li style="text-align: left;"><span>Touchscreen</span></li><li style="text-align: left;"><span>Backlit KB</span></li><li style="text-align: left;"><span>4-8 Battery Life</span></li><li style="text-align: left;"><span>One Week Personal Warranty</span></li></ul><p><span><br/></span></p><p></p><p>Package:</p><ul><li>Unit</li><li>Charger</li><li>200+ FullHD Movies</li><li>Installers Office, Photoshop, etc.</li><li>Original Box</li></ul><p><br/></p><p><i>P.S.</i></p><p><i>Please check for updates via FB Page: kwancorporation<br/>More than 1000 units sold<br/>Meetups: Taytay / Robinson’s Galleria<br/>Shipping: LBC</i></p>',
				'badge' => 'a:2:{s:5:"class";s:14:"ribbon-default";s:11:"class_array";a:1:{i:0;a:1:{s:4:"text";s:14:"ribbon-default";}}}',
				'price' => '9999.99',
				'sale_price' => NULL,
				'unit' => 2000,
				'thumbnail_id' => 61,
				'created_at' => '2015-04-22 10:45:04',
				'updated_at' => '2015-04-22 11:46:16',
				'deleted_at' => NULL,
			),
		));
	}

}
