_okie.directive 'dropzone', ->
  (scope, element, attrs) ->
    config = undefined
    dropzone = undefined
    config = scope[attrs.dropzone]
    # create a Dropzone for the element with the given options
    dropzone = new Dropzone(element[0], config.options)
    # bind the given event handlers
    angular.forEach config.eventHandlers, (handler, event) ->
      dropzone.on event, handler
      return
    return

# ---
# https://gist.github.com/compact/8118670
# generated by js2coffee 2.0.1